

USE [AQTEST];
GO

SELECT
    c.TABLE_SCHEMA,
    c.TABLE_NAME,
    t.TABLE_TYPE          -- 'BASE TABLE' or 'VIEW'
FROM INFORMATION_SCHEMA.COLUMNS AS c
JOIN INFORMATION_SCHEMA.TABLES  AS t
  ON  c.TABLE_SCHEMA = t.TABLE_SCHEMA
  AND c.TABLE_NAME   = t.TABLE_NAME
WHERE c.COLUMN_NAME = 'prop_count'
ORDER BY t.TABLE_TYPE, c.TABLE_SCHEMA, c.TABLE_NAME;
