SELECT TOP (1000) [code]
      ,[description]
      ,[user_add]
      ,[user_add_ts]
      ,[user_mod]
      ,[user_mod_ts]
      ,[pay_verify_flag]
      ,[fk_pay_arr_type_status]
      ,[rowid]
      ,[no_final_notice_flag]
      ,[fk_pay_frequency]
      ,[sms_invoice_flag]
      ,[sms_reminder_flag]
      ,[sms_final_flag]
      ,[review_date_mandatory_flag]
  FROM [AQTEST].[dbo].[pay_arr_type]
