SELECT TOP (1000) [eventnum]
      ,[eventdesc]
      ,[status_id]
      ,[status_description]
      ,[originating_workorder_num]
      ,[originating_wo_description]
      ,[originating_wo_classstructure_id]
      ,[originating_wo_class_desc]
      ,[originating_workorder_longdescription]
      ,[assetnum]
      ,[asset_desc]
      ,[location_id]
      ,[location_description]
      ,[reportedby]
      ,[targstartdate]
      ,[targcompdate]
      ,[actstart]
      ,[actfinish]
      ,[wo_esc_datetime_service_restored]
      ,[wo_esc_burstleak_priority]
      ,[all_addresses_count]
      ,[residential_customers_count]
      ,[peak_hours]
      ,[colour_test_results]
      ,[turbidity_test_results]
      ,[chlorine_test_results]
      ,[testing_time]
      ,[flushing_location]
      ,[event_type]
  FROM [src].[vw_Maximo_WaterEvents_Interruptions]
  where eventnum = 'EV22930'
