SELECT TOP (1000) [rowstamp]
      ,[assetnum]
      ,[asset_description]
      ,[location]
      ,[progress]
      ,[isprimary]
      ,[recordclass]
      ,[recordkey]
      ,[route]
      ,[routestop]
      ,[sequence]
      ,[inspformnum]
      ,[wwcreateby]
      ,[wwcreatedate]
      ,[wwenlightentrace]
      ,[wwsourceasset]
      ,[serviceaddress_addresscode]
      ,[serviceaddress_description]
      ,[regiondistrict]
      ,[postalcode]
      ,[staddrnumber]
      ,[staddrstreet]
      ,[staddrsttype]
      ,[stateprovince]
      ,[wwbilltype]
      ,[wwcreationsource]
      ,[wwdistrictcode]
      ,[wwpropertyname]
      ,[wwpropertynumber]
      ,[wwpropertywaterflag]
      ,[wwpropertyroofwaterflag]
      ,[wwpropertysewerflag]
      ,[wwpropertystatus]
      ,[wwsource]
      ,[RecordInsertDate]
  FROM [src].[vw_Maximo_WorkOrder_Event_MultiAssets]
  where [serviceaddress_addresscode] = 43087

